



SELECT TOP 10 * FROM OLTP.TABE_PRODUTO order by NEWID();

DROP TABLE IF EXISTS #TMP_PRODUTO
SELECT ID_PRODUTO_LEGADO, SUBSTRING(ID_PRODUTO_LEGADO,8,8) AS CHAVE, NOME_PRODUTO
INTO #TMP_PRODUTO
FROM OLTP.TABE_PRODUTO



SELECT DISTINCT CHAVE, NOME_PRODUTO FROM #TMP_PRODUTO

SELECT DISTINCT ID_PRODUTO_LEGADO, NOME_PRODUTO FROM #TMP_PRODUTO


--- DUPLICAÇÃO DE CHAVE
SELECT DISTINCT ID_PRODUTO_LEGADO, CHAVE, NOME_PRODUTO FROM #TMP_PRODUTO WHERE CHAVE IN (SELECT  CHAVE FROM #TMP_PRODUTO  GROUP BY CHAVE HAVING count(*) > 2) ORDER BY CHAVE ASC 


SELECT A.*, B.*, C.* FROM OLTP.TABE_PRODUTO AS A 
INNER JOIN  OLTP.TABE_CATEGORIA AS B ON A.IDCATEGORIA = B.ID_CATEGORIA
INNER JOIN OLTP.TABE_SUB_CATEGORIA AS C ON B.ID_CATEGORIA = C.IDCATEGORIA
WHERE A.ID_PRODUTO_LEGADO = 'TEC-PH-10000675'
