
/*======================================================================
|																		|
|	AUTOR		- Sergio Goncalves										|							
|	DATA		- 19/12/23												|						
|	DESCRICAO	- CRIACAO DAS TABELAS DO SISTEMA						|
|																		|
=======================================================================*/


	--- CREATE DATABASE


CREATE DATABASE OLTP_DB_STORE ;

use OLTP_DB_STORE ; 

CREATE SCHEMA OLTP AUTHORIZATION dbo ;

GO						


DROP TABLE IF EXISTS OLTP.TABE_CATEGORIA
DROP TABLE IF EXISTS OLTP.TABE_SUB_CATEGORIA
DROP TABLE IF EXISTS OLTP.TABE_ENDERECO
DROP TABLE IF EXISTS OLTP.TABE_ITEM_NOTA
DROP TABLE IF EXISTS OLTP.TABE_NOTA_FISCAL
DROP TABLE IF EXISTS OLTP.TABE_PRODUTO
DROP TABLE IF EXISTS OLTP.TABE_CLIENTE
						


							GO

						CREATE TABLE OLTP.TABE_CLIENTE (
								ID_CLIENTE					INT				NOT NULL  PRIMARY  KEY  IDENTITY (30000,1 ),
								SKU_CLIENTE					CHAR(15)		NULL,
								SKU_CLIENTE_LEGADO			CHAR(15)		NULL,
								NOME_CLIENTE_PRIMEIRO		VARCHAR(30)		NOT NULL,  
								NOME_CLIENTE_ULTIMO			VARCHAR(30)		NOT NULL, 
								NOME_CLIENTE_COMPLETO		VARCHAR(60)		NOT NULL,
								SEGMENTO					VARCHAR (20)	NOT NULL
								)


							GO
							CREATE TABLE OLTP.TABE_PRODUTO (
									 ID_PRODUTO				INT					NOT NULL PRIMARY KEY IDENTITY(10005000,7)
									,SKU_PRODUTO			CHAR		(15)
									,SKU_PRODUTO_LEGADO		CHAR		(15)
									,NOME_PRODUTO			VARCHAR		(127)	NOT NULL
									,CUSTO_PRODUTO			FLOAT		(50)	NOT NULL
									,PRECO_PRODUTO			FLOAT				NOT NULL
									,IDCATEGORIA			INT 
									)
							GO

							CREATE TABLE OLTP.TABE_CATEGORIA (
									ID_CATEGORIA	INT,
									CATEGORIA		VARCHAR(20) NOT NULL
									)
							GO

							CREATE TABLE OLTP.TABE_SUB_CATEGORIA (
									ID_SUB_CATEGORIA		INT,
									SUB_CATEGORIA			VARCHAR(20) NOT NULL,
									IDCATEGORIA				INT 
									)
							GO

							CREATE TABLE OLTP.TABE_ENDERECO (
									ID_ENDERECO		INT NOT NULL PRIMARY KEY IDENTITY(7,7),
									PAIS			VARCHAR(15) NOT NULL,
									ESTADO			VARCHAR(20) NOT NULL,
									CIDADE			VARCHAR(30) NOT NULL,
									REGIAO			VARCHAR(15) NOT NULL,
									IDCLIENTE		INT
									)
							GO

							CREATE TABLE OLTP.TABE_ITEM_NOTA (
									ID_ITEM_NOTA			INT NOT NULL PRIMARY KEY IDENTITY(1000, 3),
									SKU_PEDIDO_LEGADO		CHAR(15) NULL,
									QUANTIDADE				INT NOT NULL,
									PRECO_PRODUTO			FLOAT NOT NULL,
									DESCONTO				FLOAT NOT NULL, 
									IDPRODUTO				INT,
									IDNOTA					INT 
									)
							GO


							CREATE TABLE OLTP.TABE_NOTA_FISCAL (
									ID_NOTA					INT NOT NULL PRIMARY KEY IDENTITY (100000, 25),
									SKU_PEDIDO_LEGADO		CHAR(15),
									PRECO_TOTAL				FLOAT,
									PRECO_ANTES_DESCONTO	FLOAT,
									DESCONTO_NOTA			FLOAT,
									DATA_PEDIDO				DATE,
									ANO_MES_NOTA			CHAR(6),
									DATA_ENTREGA			DATE,
									TIPO_ENTREGA			VARCHAR(15),
									IDCLIENTE				INT
									)
							
							GO
