						
/*======================================================================
|																		|
|	AUTOR		- Sergio Goncalves										|							
|	DATA		- 19/12/23												|						
|	DESCRICAO	- CRIACAO DAS CONSTRAINTS AINDA NAO CRIADAS				|
|																		|
=======================================================================*/						
						
					USE OLTP_DB_STORE
						

						-- Criacao das Primary Keys 

							ALTER TABLE OLTP.TABE_CATEGORIA
							ALTER COLUMN ID_CATEGORIA INT NOT NULL 
							GO

							ALTER TABLE OLTP.TABE_CATEGORIA
							ADD CONSTRAINT ID_CATEGORIA  PRIMARY KEY (ID_CATEGORIA)
							GO

							ALTER TABLE OLTP.TABE_SUB_CATEGORIA
							ALTER COLUMN ID_SUB_CATEGORIA INT NOT NULL
							GO
							ALTER TABLE OLTP.TABE_SUB_CATEGORIA
							ADD CONSTRAINT ID_SUB_CATEGORIA PRIMARY KEY (ID_SUB_CATEGORIA)
							GO



							--Criacao das Foreign Keys 

							ALTER TABLE OLTP.TABE_SUB_CATEGORIA
							ALTER COLUMN IDCATEGORIA INT NOT NULL
							GO
							ALTER TABLE OLTP.TABE_SUB_CATEGORIA
							ADD FOREIGN KEY (IDCATEGORIA) REFERENCES OLTP.TABE_CATEGORIA(ID_CATEGORIA)
							GO

							ALTER TABLE OLTP.TABE_PRODUTO
							ALTER COLUMN IDCATEGORIA INT NOT NULL
							GO
							ALTER TABLE OLTP.TABE_PRODUTO
							ADD FOREIGN KEY (IDCATEGORIA) REFERENCES OLTP.TABE_CATEGORIA(ID_CATEGORIA)
							GO

							ALTER TABLE OLTP.TABE_NOTA_FISCAL
							ALTER COLUMN IDCLIENTE INT NOT NULL
							GO
							ALTER TABLE OLTP.TABE_NOTA_FISCAL
							ADD FOREIGN KEY (IDCLIENTE) REFERENCES OLTP.TABE_CLIENTE(ID_CLIENTE)
							GO

							ALTER TABLE OLTP.TABE_ENDERECO
							ALTER COLUMN IDCLIENTE INT NOT NULL
							GO
							ALTER TABLE OLTP.TABE_ENDERECO
							ADD FOREIGN KEY (IDCLIENTE) REFERENCES OLTP.TABE_CLIENTE(ID_CLIENTE)
							GO

							ALTER TABLE OLTP.TABE_ITEM_NOTA
							ALTER COLUMN IDPRODUTO INT NOT NULL

							ALTER TABLE OLTP.TABE_ITEM_NOTA
							ALTER COLUMN IDNOTA INT NOT NULL
							GO

							ALTER TABLE OLTP.TABE_ITEM_NOTA
							ADD FOREIGN KEY (IDPRODUTO) REFERENCES OLTP.TABE_PRODUTO(ID_PRODUTO)
							GO
							ALTER TABLE OLTP.TABE_ITEM_NOTA
							ADD FOREIGN KEY (IDNOTA) REFERENCES OLTP.TABE_NOTA_FISCAL(ID_NOTA)
							GO

